Rebase on Upstream 0.13.3

diff --git a/mountesp b/mountesp
--- a/mountesp
+++ b/mountesp
@@ -24,43 +24,42 @@ MountOSXESP() {
     # Identify the ESP. Note: This returns the FIRST ESP found;
     # if the system has multiple disks, this could be wrong!
     Temp=$(mount | sed -n -E "/^(\/dev\/disk.*) on \/ \(.*$/s//\1/p")
-    if [ $Temp ]; then
+    if [ "$Temp" ]; then
         Temp=$(diskutil list | grep " EFI " | grep -o 'disk.*' | head -n 1)
-        if [ -z $Temp ]; then
+        if [ -z "$Temp" ]; then
             echo "Warning: root device doesn't have an EFI partition"
         fi
     else
         echo "Warning: root device could not be found"
     fi
-    if [ -z $Temp ]; then
+    if [ -z "$Temp" ]; then
         Temp=$(diskutil list | sed -n -E '/^ *[0-9]+:[ ]+EFI EFI[ ]+[0-9.]+ [A-Z]+[ ]+(disk[0-9]+s[0-9]+)$/ { s//\1/p
                 q
             }' )
 
-        if [ -z $Temp ]; then
+        if [ -z "$Temp" ]; then
             echo "Could not find an EFI partition. Aborting!"
             exit 1
         fi
     fi
-    Esp=/dev/`echo $Temp`
+    Esp=/dev/$Temp
     echo "The ESP has been identified as $Esp; attempting to mount it...."
     # If the ESP is mounted, use its current mount point....
-    Temp=`df -P | grep "$Esp "`
-    MountPoint=`echo $Temp | cut -f 6- -d ' '`
+    Temp=$(df -P | grep "$Esp ")
+    MountPoint=$(echo "$Temp" | cut -f 6- -d ' ')
     if [[ "$MountPoint" == '' ]] ; then
         if [[ $UID != 0 ]] ; then
             echo "You must run this program as root or using sudo! Exiting!"
             exit 1
         fi
         MountPoint="/Volumes/ESP"
+        # echo "MountPoint is $MountPoint"
         mkdir /Volumes/ESP &> /dev/null
-        mount -t msdos "$Esp" $MountPoint
         # Some systems have HFS+ "ESPs." They shouldn't, but they do. If this is
         # detected, mount it as such and set appropriate options.
-        if [[ $? != 0 ]] ; then
-            mount -t hfs "$Esp" $MountPoint
-            if [[ $? != 0 ]] ; then
-                echo "Unable to mount ESP!\n"
+        if  ! mount -t msdos "$Esp" $MountPoint ; then
+            if ! mount -t hfs "$Esp" $MountPoint ; then
+                printf "Unable to mount ESP!\n\n"
                 exit 1
             fi
         fi
