Update build_and_upload_binaries.yaml

diff --git a/.github/workflows/build_and_upload_binaries.yaml b/.github/workflows/build_and_upload_binaries.yaml
--- a/.github/workflows/build_and_upload_binaries.yaml
+++ b/.github/workflows/build_and_upload_binaries.yaml
@@ -1,13 +1,12 @@
-name: Build and Upload Artifacts for RefindPlus
+name: Build and Upload Artefacts
 
 on:
-  workflow_dispatch: # Allows manual triggering of the workflow
-  push:
-    branches:
-      - GOPFix
-  pull_request:
-    branches:
-      - GOPFix
+  workflow_dispatch:
+    inputs:
+      commit_id:
+        description: "Commit ID (leave blank for GOPFix latest)"
+        required: false
+        type: number
 
 jobs:
   build-macos:
@@ -15,8 +14,10 @@ jobs:
     runs-on: macos-13
 
     steps:
-      - name: Checkout repository
+      - name: Checkout Repository
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.commit_id || 'GOPFix' }}
 
       - name: Install Python 2.7
         run: |
@@ -27,41 +28,45 @@ jobs:
         run: |
           xcode-select --install || true
 
-      - name: Set up build environment
+      - name: Prepare Build Environment
         run: |
           if [[ "${PATH}" != *"/usr/local/bin"* ]] ; then export PATH="/usr/local/bin:${PATH}"; fi
           brew install nasm
           brew install acpica
           brew install ocmtoc
-          brew install binutils
 
-      - name: Set up directory structure
+      - name: Create Directory Structure
         run: |
           mkdir -p ~/Documents/RefindPlus
 
-      - name: Clone RefindPlus repository
+      - name: Clone RefindPlus Repository
         run: |
           cd ~/Documents/RefindPlus
           git clone https://github.com/${{ github.repository_owner }}/RefindPlus.git Working
           cd Working
-          git checkout GOPFix
-          git remote add upstream https://github.com/dakanji/RefindPlus.git
 
-      - name: Clone RefindPlusUDK repository
+          # Determine which branch contains the commit
+          if [ ! -n "${{ github.event.inputs.commit_id }}" ]; then
+            BRANCH=GOPFix
+            git checkout GOPFix
+          else
+            BRANCH=$(git branch -r --contains ${{ github.event.inputs.commit_id }} | grep -v 'HEAD' | head -n 1 | sed 's/origin\///')
+            if [ -z "$BRANCH" ]; then
+              echo "Error: Commit ID not found in any remote branches!"
+              exit 1
+            fi
+            git checkout "$BRANCH"
+            git reset --hard ${{ github.event.inputs.commit_id }}
+          fi
+
+          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
+
+      - name: Clone RefindPlusUDK Repository
         run: |
           cd ~/Documents/RefindPlus
           git clone https://github.com/${{ github.repository_owner }}/RefindPlusUDK.git edk2
           cd edk2
           git checkout rudk
-          git remote add upstream https://github.com/dakanji/RefindPlusUDK.git
-          git pull upstream rudk
-
-      - name: Sync repositories
-        run: |
-          cd ~/Documents/RefindPlus/Working
-          git pull upstream GOPFix
-          cd ~/Documents/RefindPlus/edk2
-          git pull upstream rudk
 
       - name: Run Build Script
         env:
@@ -69,25 +74,36 @@ jobs:
         run: |
           cd ~/Documents/RefindPlus/edk2/000-BuildScript
           chmod +x RefindPlusBuilder.sh
-          sh RefindPlusBuilder.sh GOPFix
+          sh RefindPlusBuilder.sh "${BRANCH}" ALL
 
-      - name: Archive DEBUG build artifacts
+      - name: Archive RELEASE Build Artefacts
         if: success()
         uses: actions/upload-artifact@v4
         with:
-          name: refindplus-artifacts-debug
+          name: RefindPlus_Artefacts_REL
+          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/RELEASE_XCODE5
+          if-no-files-found: warn
+          compression-level: 6
+          overwrite: false
+          include-hidden-files: false
+
+      - name: Archive DEBUG Build Artefacts
+        if: success()
+        uses: actions/upload-artifact@v4
+        with:
+          name: RefindPlus_Artefacts_DBG
           path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/DEBUG_XCODE5
           if-no-files-found: warn
           compression-level: 6
           overwrite: false
           include-hidden-files: false
 
-      - name: Archive RELEASE build artifacts
+      - name: Archive NOOPT Build Artefacts
         if: success()
         uses: actions/upload-artifact@v4
         with:
-          name: refindplus-artifacts-release
-          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/RELEASE_XCODE5
+          name: RefindPlus_Artefacts_NPT
+          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/NOOPT_XCODE5
           if-no-files-found: warn
           compression-level: 6
           overwrite: false
